### PR TITLE
Add URL

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by samuel-marsh** [comment]
Thanks for PR.  Solved issue with Hadley's suggestion in pkgdown issue, just adding the function parentheses.  I knew it must have been something simple I was overlooking.

**Comment by maelle** [comment]
good! still a good idea to add the URL there though :slightly_smiling_face:

**Comment by samuel-marsh** [comment]
That's true.  Reopening and merging.

**Comment by samuel-marsh** [comment]
Thanks again :)

**Pull request merged**
