### PR TITLE
import DefaultDimReduc from SeuratObject

### PR DESCRIPTION
**Pull request by crazyhottommy**
It seems that DefaultDimReduc needs to be imported from the SeuratObject package. Otherwise, it will error out "DefaultDimReduc" cannot be found.

Thanks for this package!

### CODE REVIEW

**Comment by samuel-marsh** [comment]
Hi Ming!

Can you provide example code that is providing the error?  I can certainly add the `importFrom` to the necessary functions but since scCustomize attaches Seurat on load and Seurat attaches SeuratObject and that function is now exported from SeuratObject then I think it should run without the direct `importFrom` call but I could be wrong.

Thanks!!
Sam

**Comment by crazyhottommy** [comment]
It could be my Seurat installation issues.  I see in your code, many functions use `DefaultDimReduc`. The one I tried `FeaturePlot_scCustom`.  

adding importFrom(SeuratObject,DefaultDimReduc) fixed the problem on my side. If you do a fresh installation and no problem for you, then please ignore this.

Thanks!

**Comment by samuel-marsh** [comment]
So it looks like it built fine with fresh install.  Installing package should force SeuratObject to update to 4.0.3 if not already which exports the function.  

Regardless though to keep good package practices I'm going to specify the importFrom shortly in the dev branch.  Just waiting to make sure newly implemented continuous integration checks work first.  I'm going to close this but will post here when changes are made in dev branch.

Thanks!!
Sam

**Comment by crazyhottommy** [comment]
Thanks! "SeuratObject to update to 4.0.3 if not already which exports the function." I believe I had 4.0.2 and I saw the error message.

**Comment by samuel-marsh** [comment]
@crazyhottommy glad it's all working.  Now explicitly specified in develop branch v0.6.2.0002.

Best!
Sam

**Pull request closed without merging**
